//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: as_c_proto.proto
namespace as_c_proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"c_as_register_req")]
  public partial class c_as_register_req : global::ProtoBuf.IExtensible
  {
    public c_as_register_req() {}
    
    private int _plantform_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"plantform_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int plantform_id
    {
      get { return _plantform_id; }
      set { _plantform_id = value; }
    }
    private int _plantform_sub_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"plantform_sub_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int plantform_sub_id
    {
      get { return _plantform_sub_id; }
      set { _plantform_sub_id = value; }
    }
    private string _account;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"account", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string account
    {
      get { return _account; }
      set { _account = value; }
    }
    private string _password;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"password", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string password
    {
      get { return _password; }
      set { _password = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"as_c_register_res")]
  public partial class as_c_register_res : global::ProtoBuf.IExtensible
  {
    public as_c_register_res() {}
    
    private int _error_code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"error_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int error_code
    {
      get { return _error_code; }
      set { _error_code = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"c_as_login_req")]
  public partial class c_as_login_req : global::ProtoBuf.IExtensible
  {
    public c_as_login_req() {}
    
    private int _plantform_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"plantform_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int plantform_id
    {
      get { return _plantform_id; }
      set { _plantform_id = value; }
    }
    private int _plantform_sub_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"plantform_sub_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int plantform_sub_id
    {
      get { return _plantform_sub_id; }
      set { _plantform_sub_id = value; }
    }
    private string _account;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"account", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string account
    {
      get { return _account; }
      set { _account = value; }
    }
    private string _password;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"password", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string password
    {
      get { return _password; }
      set { _password = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"area")]
  public partial class area : global::ProtoBuf.IExtensible
  {
    public area() {}
    
    private int _area_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"area_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int area_id
    {
      get { return _area_id; }
      set { _area_id = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private int _status = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int status
    {
      get { return _status; }
      set { _status = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"EAreaStatus")]
    public enum EAreaStatus
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"EAreaStatus_None", Value=0)]
      EAreaStatus_None = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EAreaStatus_Good", Value=1)]
      EAreaStatus_Good = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EAreaStatus_Normal", Value=2)]
      EAreaStatus_Normal = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EAreaStatus_Bad", Value=3)]
      EAreaStatus_Bad = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EAreaStatus_New", Value=4)]
      EAreaStatus_New = 4
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"area_list")]
  public partial class area_list : global::ProtoBuf.IExtensible
  {
    public area_list() {}
    
    private readonly global::System.Collections.Generic.List<area> _areas = new global::System.Collections.Generic.List<area>();
    [global::ProtoBuf.ProtoMember(1, Name=@"areas", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<area> areas
    {
      get { return _areas; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"as_c_login_res")]
  public partial class as_c_login_res : global::ProtoBuf.IExtensible
  {
    public as_c_login_res() {}
    
    private int _error_code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"error_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int error_code
    {
      get { return _error_code; }
      set { _error_code = value; }
    }
    private area_list _areas = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"areas", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public area_list areas
    {
      get { return _areas; }
      set { _areas = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"c_as_login_if_no_register_req")]
  public partial class c_as_login_if_no_register_req : global::ProtoBuf.IExtensible
  {
    public c_as_login_if_no_register_req() {}
    
    private int _plantform_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"plantform_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int plantform_id
    {
      get { return _plantform_id; }
      set { _plantform_id = value; }
    }
    private int _plantform_sub_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"plantform_sub_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int plantform_sub_id
    {
      get { return _plantform_sub_id; }
      set { _plantform_sub_id = value; }
    }
    private string _account;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"account", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string account
    {
      get { return _account; }
      set { _account = value; }
    }
    private string _password;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"password", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string password
    {
      get { return _password; }
      set { _password = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"as_c_login_if_no_register_res")]
  public partial class as_c_login_if_no_register_res : global::ProtoBuf.IExtensible
  {
    public as_c_login_if_no_register_res() {}
    
    private int _error_code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"error_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int error_code
    {
      get { return _error_code; }
      set { _error_code = value; }
    }
    private area_list _areas = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"areas", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public area_list areas
    {
      get { return _areas; }
      set { _areas = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"c_as_enter_area_req")]
  public partial class c_as_enter_area_req : global::ProtoBuf.IExtensible
  {
    public c_as_enter_area_req() {}
    
    private int _area_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"area_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int area_id
    {
      get { return _area_id; }
      set { _area_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"as_c_enter_area_res")]
  public partial class as_c_enter_area_res : global::ProtoBuf.IExtensible
  {
    public as_c_enter_area_res() {}
    
    private int _error_code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"error_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int error_code
    {
      get { return _error_code; }
      set { _error_code = value; }
    }
    private string _ip = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"ip", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string ip
    {
      get { return _ip; }
      set { _ip = value; }
    }
    private int _port = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"port", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int port
    {
      get { return _port; }
      set { _port = value; }
    }
    private byte[] _token = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"token", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] token
    {
      get { return _token; }
      set { _token = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"c_as_logout_req")]
  public partial class c_as_logout_req : global::ProtoBuf.IExtensible
  {
    public c_as_logout_req() {}
    
    private int _plantform_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"plantform_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int plantform_id
    {
      get { return _plantform_id; }
      set { _plantform_id = value; }
    }
    private int _plantform_sub_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"plantform_sub_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int plantform_sub_id
    {
      get { return _plantform_sub_id; }
      set { _plantform_sub_id = value; }
    }
    private string _account;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"account", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string account
    {
      get { return _account; }
      set { _account = value; }
    }
    private string _password;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"password", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string password
    {
      get { return _password; }
      set { _password = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"as_c_logout_res")]
  public partial class as_c_logout_res : global::ProtoBuf.IExtensible
  {
    public as_c_logout_res() {}
    
    private int _error_code = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"error_code", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int error_code
    {
      get { return _error_code; }
      set { _error_code = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"e_asc_proto_version")]
    public enum e_asc_proto_version
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ASC_VERSION", Value=1)]
      ASC_VERSION = 1
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"e_msg_c_as")]
    public enum e_msg_c_as
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"e_msg_c_as_min", Value=0)]
      e_msg_c_as_min = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"e_msg_c_as_register_req", Value=1)]
      e_msg_c_as_register_req = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"e_msg_c_as_login_req", Value=2)]
      e_msg_c_as_login_req = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"e_msg_c_as_enter_area_req", Value=3)]
      e_msg_c_as_enter_area_req = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"e_msg_c_as_logout_req", Value=4)]
      e_msg_c_as_logout_req = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"e_msg_c_as_login_if_no_register_req", Value=5)]
      e_msg_c_as_login_if_no_register_req = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"e_msg_c_as_max", Value=6)]
      e_msg_c_as_max = 6
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"e_msg_as_c")]
    public enum e_msg_as_c
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"e_msg_as_c_min", Value=0)]
      e_msg_as_c_min = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"e_msg_as_c_register_res", Value=1)]
      e_msg_as_c_register_res = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"e_msg_as_c_login_res", Value=2)]
      e_msg_as_c_login_res = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"e_msg_as_c_enter_area_res", Value=3)]
      e_msg_as_c_enter_area_res = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"e_msg_as_c_logout_res", Value=4)]
      e_msg_as_c_logout_res = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"e_msg_as_c_login_if_no_register_res", Value=5)]
      e_msg_as_c_login_if_no_register_res = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"e_msg_as_c_max", Value=6)]
      e_msg_as_c_max = 6
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"e_asc_errorcode")]
    public enum e_asc_errorcode
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"e_asc_errorcode_min", Value=0)]
      e_asc_errorcode_min = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"e_asc_errorcode_success", Value=1)]
      e_asc_errorcode_success = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"e_asc_errorcode_unkown_error", Value=2)]
      e_asc_errorcode_unkown_error = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"e_asc_errorcode_registe_already", Value=3)]
      e_asc_errorcode_registe_already = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"e_asc_errorcode_account_not_exist_or_wrong_password", Value=4)]
      e_asc_errorcode_account_not_exist_or_wrong_password = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"e_asc_errorcode_not_logined", Value=5)]
      e_asc_errorcode_not_logined = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"e_asc_errorcode_no_this_area", Value=6)]
      e_asc_errorcode_no_this_area = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"e_asc_errorcode_area_closed", Value=7)]
      e_asc_errorcode_area_closed = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"e_asc_errorcode_wrong_password", Value=8)]
      e_asc_errorcode_wrong_password = 8,
            
      [global::ProtoBuf.ProtoEnum(Name=@"e_asc_errorcode_max", Value=9)]
      e_asc_errorcode_max = 9
    }
  
}