// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gs_gm_proto.proto

#ifndef PROTOBUF_gs_5fgm_5fproto_2eproto__INCLUDED
#define PROTOBUF_gs_5fgm_5fproto_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_gs_5fgm_5fproto_2eproto();
void protobuf_AssignDesc_gs_5fgm_5fproto_2eproto();
void protobuf_ShutdownFile_gs_5fgm_5fproto_2eproto();

class game_element;
class gm_gs_add_item_req;
class gs_gm_add_item_res;
class gm_gs_marquee_req;
class gs_gm_marquee_res;
class gm_gs_mail_req;
class gs_gm_mail_res;
class gm_gs_arena_mail_req;
class gs_gm_arena_mail_res;

enum gm_gs_marquee_req_MARQUEE_TYPE {
  gm_gs_marquee_req_MARQUEE_TYPE_MARQUEE_WORD = 6
};
bool gm_gs_marquee_req_MARQUEE_TYPE_IsValid(int value);
const gm_gs_marquee_req_MARQUEE_TYPE gm_gs_marquee_req_MARQUEE_TYPE_MARQUEE_TYPE_MIN = gm_gs_marquee_req_MARQUEE_TYPE_MARQUEE_WORD;
const gm_gs_marquee_req_MARQUEE_TYPE gm_gs_marquee_req_MARQUEE_TYPE_MARQUEE_TYPE_MAX = gm_gs_marquee_req_MARQUEE_TYPE_MARQUEE_WORD;
const int gm_gs_marquee_req_MARQUEE_TYPE_MARQUEE_TYPE_ARRAYSIZE = gm_gs_marquee_req_MARQUEE_TYPE_MARQUEE_TYPE_MAX + 1;

const ::google::protobuf::EnumDescriptor* gm_gs_marquee_req_MARQUEE_TYPE_descriptor();
inline const ::std::string& gm_gs_marquee_req_MARQUEE_TYPE_Name(gm_gs_marquee_req_MARQUEE_TYPE value) {
  return ::google::protobuf::internal::NameOfEnum(
    gm_gs_marquee_req_MARQUEE_TYPE_descriptor(), value);
}
inline bool gm_gs_marquee_req_MARQUEE_TYPE_Parse(
    const ::std::string& name, gm_gs_marquee_req_MARQUEE_TYPE* value) {
  return ::google::protobuf::internal::ParseNamedEnum<gm_gs_marquee_req_MARQUEE_TYPE>(
    gm_gs_marquee_req_MARQUEE_TYPE_descriptor(), name, value);
}
enum gm_gs_mail_req_MAIL_TYPE {
  gm_gs_mail_req_MAIL_TYPE_MAIL_TYPE_SYS_NOTICE = 6
};
bool gm_gs_mail_req_MAIL_TYPE_IsValid(int value);
const gm_gs_mail_req_MAIL_TYPE gm_gs_mail_req_MAIL_TYPE_MAIL_TYPE_MIN = gm_gs_mail_req_MAIL_TYPE_MAIL_TYPE_SYS_NOTICE;
const gm_gs_mail_req_MAIL_TYPE gm_gs_mail_req_MAIL_TYPE_MAIL_TYPE_MAX = gm_gs_mail_req_MAIL_TYPE_MAIL_TYPE_SYS_NOTICE;
const int gm_gs_mail_req_MAIL_TYPE_MAIL_TYPE_ARRAYSIZE = gm_gs_mail_req_MAIL_TYPE_MAIL_TYPE_MAX + 1;

const ::google::protobuf::EnumDescriptor* gm_gs_mail_req_MAIL_TYPE_descriptor();
inline const ::std::string& gm_gs_mail_req_MAIL_TYPE_Name(gm_gs_mail_req_MAIL_TYPE value) {
  return ::google::protobuf::internal::NameOfEnum(
    gm_gs_mail_req_MAIL_TYPE_descriptor(), value);
}
inline bool gm_gs_mail_req_MAIL_TYPE_Parse(
    const ::std::string& name, gm_gs_mail_req_MAIL_TYPE* value) {
  return ::google::protobuf::internal::ParseNamedEnum<gm_gs_mail_req_MAIL_TYPE>(
    gm_gs_mail_req_MAIL_TYPE_descriptor(), name, value);
}
enum e_gsgm_proto_version {
  GSGM_VERSION = 1
};
bool e_gsgm_proto_version_IsValid(int value);
const e_gsgm_proto_version e_gsgm_proto_version_MIN = GSGM_VERSION;
const e_gsgm_proto_version e_gsgm_proto_version_MAX = GSGM_VERSION;
const int e_gsgm_proto_version_ARRAYSIZE = e_gsgm_proto_version_MAX + 1;

const ::google::protobuf::EnumDescriptor* e_gsgm_proto_version_descriptor();
inline const ::std::string& e_gsgm_proto_version_Name(e_gsgm_proto_version value) {
  return ::google::protobuf::internal::NameOfEnum(
    e_gsgm_proto_version_descriptor(), value);
}
inline bool e_gsgm_proto_version_Parse(
    const ::std::string& name, e_gsgm_proto_version* value) {
  return ::google::protobuf::internal::ParseNamedEnum<e_gsgm_proto_version>(
    e_gsgm_proto_version_descriptor(), name, value);
}
enum e_msg_gm_gs {
  e_msg_gm_gs_min = 0,
  e_msg_gm_gs_marquee_req = 1,
  e_msg_gm_gs_add_item_req = 2,
  e_msg_gm_gs_mail_req = 3,
  e_msg_gm_gs_arena_mail_req = 4,
  e_msg_gm_gs_max = 5
};
bool e_msg_gm_gs_IsValid(int value);
const e_msg_gm_gs e_msg_gm_gs_MIN = e_msg_gm_gs_min;
const e_msg_gm_gs e_msg_gm_gs_MAX = e_msg_gm_gs_max;
const int e_msg_gm_gs_ARRAYSIZE = e_msg_gm_gs_MAX + 1;

const ::google::protobuf::EnumDescriptor* e_msg_gm_gs_descriptor();
inline const ::std::string& e_msg_gm_gs_Name(e_msg_gm_gs value) {
  return ::google::protobuf::internal::NameOfEnum(
    e_msg_gm_gs_descriptor(), value);
}
inline bool e_msg_gm_gs_Parse(
    const ::std::string& name, e_msg_gm_gs* value) {
  return ::google::protobuf::internal::ParseNamedEnum<e_msg_gm_gs>(
    e_msg_gm_gs_descriptor(), name, value);
}
enum e_msg_gs_gm {
  e_msg_gs_gm_min = 0,
  e_msg_gs_gm_marquee_res = 1,
  e_msg_gs_gm_add_item_res = 2,
  e_msg_gs_gm_mail_res = 3,
  e_msg_gs_gm_arena_mail_res = 4,
  e_msg_gs_gm_max = 5
};
bool e_msg_gs_gm_IsValid(int value);
const e_msg_gs_gm e_msg_gs_gm_MIN = e_msg_gs_gm_min;
const e_msg_gs_gm e_msg_gs_gm_MAX = e_msg_gs_gm_max;
const int e_msg_gs_gm_ARRAYSIZE = e_msg_gs_gm_MAX + 1;

const ::google::protobuf::EnumDescriptor* e_msg_gs_gm_descriptor();
inline const ::std::string& e_msg_gs_gm_Name(e_msg_gs_gm value) {
  return ::google::protobuf::internal::NameOfEnum(
    e_msg_gs_gm_descriptor(), value);
}
inline bool e_msg_gs_gm_Parse(
    const ::std::string& name, e_msg_gs_gm* value) {
  return ::google::protobuf::internal::ParseNamedEnum<e_msg_gs_gm>(
    e_msg_gs_gm_descriptor(), name, value);
}
enum e_gsgm_errorcode {
  e_gsgm_errorcode_min = 0,
  e_gsgm_errorcode_success = 1,
  e_gsgm_errorcode_unkown_error = 2,
  e_gsgm_errorcode_user_not_online = 3,
  e_gsgm_errorcode_max = 4
};
bool e_gsgm_errorcode_IsValid(int value);
const e_gsgm_errorcode e_gsgm_errorcode_MIN = e_gsgm_errorcode_min;
const e_gsgm_errorcode e_gsgm_errorcode_MAX = e_gsgm_errorcode_max;
const int e_gsgm_errorcode_ARRAYSIZE = e_gsgm_errorcode_MAX + 1;

const ::google::protobuf::EnumDescriptor* e_gsgm_errorcode_descriptor();
inline const ::std::string& e_gsgm_errorcode_Name(e_gsgm_errorcode value) {
  return ::google::protobuf::internal::NameOfEnum(
    e_gsgm_errorcode_descriptor(), value);
}
inline bool e_gsgm_errorcode_Parse(
    const ::std::string& name, e_gsgm_errorcode* value) {
  return ::google::protobuf::internal::ParseNamedEnum<e_gsgm_errorcode>(
    e_gsgm_errorcode_descriptor(), name, value);
}
// ===================================================================

class game_element : public ::google::protobuf::Message {
 public:
  game_element();
  virtual ~game_element();

  game_element(const game_element& from);

  inline game_element& operator=(const game_element& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const game_element& default_instance();

  void Swap(game_element* other);

  // implements Message ----------------------------------------------

  game_element* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const game_element& from);
  void MergeFrom(const game_element& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 type = 1;
  inline bool has_type() const;
  inline void clear_type();
  static const int kTypeFieldNumber = 1;
  inline ::google::protobuf::uint32 type() const;
  inline void set_type(::google::protobuf::uint32 value);

  // required uint32 id = 2;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 2;
  inline ::google::protobuf::uint32 id() const;
  inline void set_id(::google::protobuf::uint32 value);

  // required uint32 num = 3;
  inline bool has_num() const;
  inline void clear_num();
  static const int kNumFieldNumber = 3;
  inline ::google::protobuf::uint32 num() const;
  inline void set_num(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:game_element)
 private:
  inline void set_has_type();
  inline void clear_has_type();
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_num();
  inline void clear_has_num();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 type_;
  ::google::protobuf::uint32 id_;
  ::google::protobuf::uint32 num_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];

  friend void  protobuf_AddDesc_gs_5fgm_5fproto_2eproto();
  friend void protobuf_AssignDesc_gs_5fgm_5fproto_2eproto();
  friend void protobuf_ShutdownFile_gs_5fgm_5fproto_2eproto();

  void InitAsDefaultInstance();
  static game_element* default_instance_;
};
// -------------------------------------------------------------------

class gm_gs_add_item_req : public ::google::protobuf::Message {
 public:
  gm_gs_add_item_req();
  virtual ~gm_gs_add_item_req();

  gm_gs_add_item_req(const gm_gs_add_item_req& from);

  inline gm_gs_add_item_req& operator=(const gm_gs_add_item_req& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const gm_gs_add_item_req& default_instance();

  void Swap(gm_gs_add_item_req* other);

  // implements Message ----------------------------------------------

  gm_gs_add_item_req* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const gm_gs_add_item_req& from);
  void MergeFrom(const gm_gs_add_item_req& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 user_id = 1;
  inline bool has_user_id() const;
  inline void clear_user_id();
  static const int kUserIdFieldNumber = 1;
  inline ::google::protobuf::uint32 user_id() const;
  inline void set_user_id(::google::protobuf::uint32 value);

  // required uint32 item_id = 2;
  inline bool has_item_id() const;
  inline void clear_item_id();
  static const int kItemIdFieldNumber = 2;
  inline ::google::protobuf::uint32 item_id() const;
  inline void set_item_id(::google::protobuf::uint32 value);

  // required uint32 num = 3;
  inline bool has_num() const;
  inline void clear_num();
  static const int kNumFieldNumber = 3;
  inline ::google::protobuf::uint32 num() const;
  inline void set_num(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:gm_gs_add_item_req)
 private:
  inline void set_has_user_id();
  inline void clear_has_user_id();
  inline void set_has_item_id();
  inline void clear_has_item_id();
  inline void set_has_num();
  inline void clear_has_num();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 user_id_;
  ::google::protobuf::uint32 item_id_;
  ::google::protobuf::uint32 num_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];

  friend void  protobuf_AddDesc_gs_5fgm_5fproto_2eproto();
  friend void protobuf_AssignDesc_gs_5fgm_5fproto_2eproto();
  friend void protobuf_ShutdownFile_gs_5fgm_5fproto_2eproto();

  void InitAsDefaultInstance();
  static gm_gs_add_item_req* default_instance_;
};
// -------------------------------------------------------------------

class gs_gm_add_item_res : public ::google::protobuf::Message {
 public:
  gs_gm_add_item_res();
  virtual ~gs_gm_add_item_res();

  gs_gm_add_item_res(const gs_gm_add_item_res& from);

  inline gs_gm_add_item_res& operator=(const gs_gm_add_item_res& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const gs_gm_add_item_res& default_instance();

  void Swap(gs_gm_add_item_res* other);

  // implements Message ----------------------------------------------

  gs_gm_add_item_res* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const gs_gm_add_item_res& from);
  void MergeFrom(const gs_gm_add_item_res& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 error_code = 1;
  inline bool has_error_code() const;
  inline void clear_error_code();
  static const int kErrorCodeFieldNumber = 1;
  inline ::google::protobuf::int32 error_code() const;
  inline void set_error_code(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:gs_gm_add_item_res)
 private:
  inline void set_has_error_code();
  inline void clear_has_error_code();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 error_code_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_gs_5fgm_5fproto_2eproto();
  friend void protobuf_AssignDesc_gs_5fgm_5fproto_2eproto();
  friend void protobuf_ShutdownFile_gs_5fgm_5fproto_2eproto();

  void InitAsDefaultInstance();
  static gs_gm_add_item_res* default_instance_;
};
// -------------------------------------------------------------------

class gm_gs_marquee_req : public ::google::protobuf::Message {
 public:
  gm_gs_marquee_req();
  virtual ~gm_gs_marquee_req();

  gm_gs_marquee_req(const gm_gs_marquee_req& from);

  inline gm_gs_marquee_req& operator=(const gm_gs_marquee_req& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const gm_gs_marquee_req& default_instance();

  void Swap(gm_gs_marquee_req* other);

  // implements Message ----------------------------------------------

  gm_gs_marquee_req* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const gm_gs_marquee_req& from);
  void MergeFrom(const gm_gs_marquee_req& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef gm_gs_marquee_req_MARQUEE_TYPE MARQUEE_TYPE;
  static const MARQUEE_TYPE MARQUEE_WORD = gm_gs_marquee_req_MARQUEE_TYPE_MARQUEE_WORD;
  static inline bool MARQUEE_TYPE_IsValid(int value) {
    return gm_gs_marquee_req_MARQUEE_TYPE_IsValid(value);
  }
  static const MARQUEE_TYPE MARQUEE_TYPE_MIN =
    gm_gs_marquee_req_MARQUEE_TYPE_MARQUEE_TYPE_MIN;
  static const MARQUEE_TYPE MARQUEE_TYPE_MAX =
    gm_gs_marquee_req_MARQUEE_TYPE_MARQUEE_TYPE_MAX;
  static const int MARQUEE_TYPE_ARRAYSIZE =
    gm_gs_marquee_req_MARQUEE_TYPE_MARQUEE_TYPE_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  MARQUEE_TYPE_descriptor() {
    return gm_gs_marquee_req_MARQUEE_TYPE_descriptor();
  }
  static inline const ::std::string& MARQUEE_TYPE_Name(MARQUEE_TYPE value) {
    return gm_gs_marquee_req_MARQUEE_TYPE_Name(value);
  }
  static inline bool MARQUEE_TYPE_Parse(const ::std::string& name,
      MARQUEE_TYPE* value) {
    return gm_gs_marquee_req_MARQUEE_TYPE_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // required .gm_gs_marquee_req.MARQUEE_TYPE type = 1;
  inline bool has_type() const;
  inline void clear_type();
  static const int kTypeFieldNumber = 1;
  inline ::gm_gs_marquee_req_MARQUEE_TYPE type() const;
  inline void set_type(::gm_gs_marquee_req_MARQUEE_TYPE value);

  // required string content = 2;
  inline bool has_content() const;
  inline void clear_content();
  static const int kContentFieldNumber = 2;
  inline const ::std::string& content() const;
  inline void set_content(const ::std::string& value);
  inline void set_content(const char* value);
  inline void set_content(const char* value, size_t size);
  inline ::std::string* mutable_content();
  inline ::std::string* release_content();
  inline void set_allocated_content(::std::string* content);

  // @@protoc_insertion_point(class_scope:gm_gs_marquee_req)
 private:
  inline void set_has_type();
  inline void clear_has_type();
  inline void set_has_content();
  inline void clear_has_content();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* content_;
  int type_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_gs_5fgm_5fproto_2eproto();
  friend void protobuf_AssignDesc_gs_5fgm_5fproto_2eproto();
  friend void protobuf_ShutdownFile_gs_5fgm_5fproto_2eproto();

  void InitAsDefaultInstance();
  static gm_gs_marquee_req* default_instance_;
};
// -------------------------------------------------------------------

class gs_gm_marquee_res : public ::google::protobuf::Message {
 public:
  gs_gm_marquee_res();
  virtual ~gs_gm_marquee_res();

  gs_gm_marquee_res(const gs_gm_marquee_res& from);

  inline gs_gm_marquee_res& operator=(const gs_gm_marquee_res& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const gs_gm_marquee_res& default_instance();

  void Swap(gs_gm_marquee_res* other);

  // implements Message ----------------------------------------------

  gs_gm_marquee_res* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const gs_gm_marquee_res& from);
  void MergeFrom(const gs_gm_marquee_res& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 error_code = 1;
  inline bool has_error_code() const;
  inline void clear_error_code();
  static const int kErrorCodeFieldNumber = 1;
  inline ::google::protobuf::int32 error_code() const;
  inline void set_error_code(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:gs_gm_marquee_res)
 private:
  inline void set_has_error_code();
  inline void clear_has_error_code();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 error_code_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_gs_5fgm_5fproto_2eproto();
  friend void protobuf_AssignDesc_gs_5fgm_5fproto_2eproto();
  friend void protobuf_ShutdownFile_gs_5fgm_5fproto_2eproto();

  void InitAsDefaultInstance();
  static gs_gm_marquee_res* default_instance_;
};
// -------------------------------------------------------------------

class gm_gs_mail_req : public ::google::protobuf::Message {
 public:
  gm_gs_mail_req();
  virtual ~gm_gs_mail_req();

  gm_gs_mail_req(const gm_gs_mail_req& from);

  inline gm_gs_mail_req& operator=(const gm_gs_mail_req& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const gm_gs_mail_req& default_instance();

  void Swap(gm_gs_mail_req* other);

  // implements Message ----------------------------------------------

  gm_gs_mail_req* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const gm_gs_mail_req& from);
  void MergeFrom(const gm_gs_mail_req& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef gm_gs_mail_req_MAIL_TYPE MAIL_TYPE;
  static const MAIL_TYPE MAIL_TYPE_SYS_NOTICE = gm_gs_mail_req_MAIL_TYPE_MAIL_TYPE_SYS_NOTICE;
  static inline bool MAIL_TYPE_IsValid(int value) {
    return gm_gs_mail_req_MAIL_TYPE_IsValid(value);
  }
  static const MAIL_TYPE MAIL_TYPE_MIN =
    gm_gs_mail_req_MAIL_TYPE_MAIL_TYPE_MIN;
  static const MAIL_TYPE MAIL_TYPE_MAX =
    gm_gs_mail_req_MAIL_TYPE_MAIL_TYPE_MAX;
  static const int MAIL_TYPE_ARRAYSIZE =
    gm_gs_mail_req_MAIL_TYPE_MAIL_TYPE_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  MAIL_TYPE_descriptor() {
    return gm_gs_mail_req_MAIL_TYPE_descriptor();
  }
  static inline const ::std::string& MAIL_TYPE_Name(MAIL_TYPE value) {
    return gm_gs_mail_req_MAIL_TYPE_Name(value);
  }
  static inline bool MAIL_TYPE_Parse(const ::std::string& name,
      MAIL_TYPE* value) {
    return gm_gs_mail_req_MAIL_TYPE_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // required .gm_gs_mail_req.MAIL_TYPE type = 1;
  inline bool has_type() const;
  inline void clear_type();
  static const int kTypeFieldNumber = 1;
  inline ::gm_gs_mail_req_MAIL_TYPE type() const;
  inline void set_type(::gm_gs_mail_req_MAIL_TYPE value);

  // repeated uint32 users = 2;
  inline int users_size() const;
  inline void clear_users();
  static const int kUsersFieldNumber = 2;
  inline ::google::protobuf::uint32 users(int index) const;
  inline void set_users(int index, ::google::protobuf::uint32 value);
  inline void add_users(::google::protobuf::uint32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
      users() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
      mutable_users();

  // required string content = 3;
  inline bool has_content() const;
  inline void clear_content();
  static const int kContentFieldNumber = 3;
  inline const ::std::string& content() const;
  inline void set_content(const ::std::string& value);
  inline void set_content(const char* value);
  inline void set_content(const char* value, size_t size);
  inline ::std::string* mutable_content();
  inline ::std::string* release_content();
  inline void set_allocated_content(::std::string* content);

  // repeated .game_element elements = 4;
  inline int elements_size() const;
  inline void clear_elements();
  static const int kElementsFieldNumber = 4;
  inline const ::game_element& elements(int index) const;
  inline ::game_element* mutable_elements(int index);
  inline ::game_element* add_elements();
  inline const ::google::protobuf::RepeatedPtrField< ::game_element >&
      elements() const;
  inline ::google::protobuf::RepeatedPtrField< ::game_element >*
      mutable_elements();

  // @@protoc_insertion_point(class_scope:gm_gs_mail_req)
 private:
  inline void set_has_type();
  inline void clear_has_type();
  inline void set_has_content();
  inline void clear_has_content();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedField< ::google::protobuf::uint32 > users_;
  ::std::string* content_;
  ::google::protobuf::RepeatedPtrField< ::game_element > elements_;
  int type_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(4 + 31) / 32];

  friend void  protobuf_AddDesc_gs_5fgm_5fproto_2eproto();
  friend void protobuf_AssignDesc_gs_5fgm_5fproto_2eproto();
  friend void protobuf_ShutdownFile_gs_5fgm_5fproto_2eproto();

  void InitAsDefaultInstance();
  static gm_gs_mail_req* default_instance_;
};
// -------------------------------------------------------------------

class gs_gm_mail_res : public ::google::protobuf::Message {
 public:
  gs_gm_mail_res();
  virtual ~gs_gm_mail_res();

  gs_gm_mail_res(const gs_gm_mail_res& from);

  inline gs_gm_mail_res& operator=(const gs_gm_mail_res& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const gs_gm_mail_res& default_instance();

  void Swap(gs_gm_mail_res* other);

  // implements Message ----------------------------------------------

  gs_gm_mail_res* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const gs_gm_mail_res& from);
  void MergeFrom(const gs_gm_mail_res& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 error_code = 1;
  inline bool has_error_code() const;
  inline void clear_error_code();
  static const int kErrorCodeFieldNumber = 1;
  inline ::google::protobuf::int32 error_code() const;
  inline void set_error_code(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:gs_gm_mail_res)
 private:
  inline void set_has_error_code();
  inline void clear_has_error_code();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 error_code_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_gs_5fgm_5fproto_2eproto();
  friend void protobuf_AssignDesc_gs_5fgm_5fproto_2eproto();
  friend void protobuf_ShutdownFile_gs_5fgm_5fproto_2eproto();

  void InitAsDefaultInstance();
  static gs_gm_mail_res* default_instance_;
};
// -------------------------------------------------------------------

class gm_gs_arena_mail_req : public ::google::protobuf::Message {
 public:
  gm_gs_arena_mail_req();
  virtual ~gm_gs_arena_mail_req();

  gm_gs_arena_mail_req(const gm_gs_arena_mail_req& from);

  inline gm_gs_arena_mail_req& operator=(const gm_gs_arena_mail_req& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const gm_gs_arena_mail_req& default_instance();

  void Swap(gm_gs_arena_mail_req* other);

  // implements Message ----------------------------------------------

  gm_gs_arena_mail_req* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const gm_gs_arena_mail_req& from);
  void MergeFrom(const gm_gs_arena_mail_req& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:gm_gs_arena_mail_req)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;


  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[1];

  friend void  protobuf_AddDesc_gs_5fgm_5fproto_2eproto();
  friend void protobuf_AssignDesc_gs_5fgm_5fproto_2eproto();
  friend void protobuf_ShutdownFile_gs_5fgm_5fproto_2eproto();

  void InitAsDefaultInstance();
  static gm_gs_arena_mail_req* default_instance_;
};
// -------------------------------------------------------------------

class gs_gm_arena_mail_res : public ::google::protobuf::Message {
 public:
  gs_gm_arena_mail_res();
  virtual ~gs_gm_arena_mail_res();

  gs_gm_arena_mail_res(const gs_gm_arena_mail_res& from);

  inline gs_gm_arena_mail_res& operator=(const gs_gm_arena_mail_res& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const gs_gm_arena_mail_res& default_instance();

  void Swap(gs_gm_arena_mail_res* other);

  // implements Message ----------------------------------------------

  gs_gm_arena_mail_res* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const gs_gm_arena_mail_res& from);
  void MergeFrom(const gs_gm_arena_mail_res& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 error_code = 1;
  inline bool has_error_code() const;
  inline void clear_error_code();
  static const int kErrorCodeFieldNumber = 1;
  inline ::google::protobuf::int32 error_code() const;
  inline void set_error_code(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:gs_gm_arena_mail_res)
 private:
  inline void set_has_error_code();
  inline void clear_has_error_code();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 error_code_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_gs_5fgm_5fproto_2eproto();
  friend void protobuf_AssignDesc_gs_5fgm_5fproto_2eproto();
  friend void protobuf_ShutdownFile_gs_5fgm_5fproto_2eproto();

  void InitAsDefaultInstance();
  static gs_gm_arena_mail_res* default_instance_;
};
// ===================================================================


// ===================================================================

// game_element

// required uint32 type = 1;
inline bool game_element::has_type() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void game_element::set_has_type() {
  _has_bits_[0] |= 0x00000001u;
}
inline void game_element::clear_has_type() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void game_element::clear_type() {
  type_ = 0u;
  clear_has_type();
}
inline ::google::protobuf::uint32 game_element::type() const {
  return type_;
}
inline void game_element::set_type(::google::protobuf::uint32 value) {
  set_has_type();
  type_ = value;
}

// required uint32 id = 2;
inline bool game_element::has_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void game_element::set_has_id() {
  _has_bits_[0] |= 0x00000002u;
}
inline void game_element::clear_has_id() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void game_element::clear_id() {
  id_ = 0u;
  clear_has_id();
}
inline ::google::protobuf::uint32 game_element::id() const {
  return id_;
}
inline void game_element::set_id(::google::protobuf::uint32 value) {
  set_has_id();
  id_ = value;
}

// required uint32 num = 3;
inline bool game_element::has_num() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void game_element::set_has_num() {
  _has_bits_[0] |= 0x00000004u;
}
inline void game_element::clear_has_num() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void game_element::clear_num() {
  num_ = 0u;
  clear_has_num();
}
inline ::google::protobuf::uint32 game_element::num() const {
  return num_;
}
inline void game_element::set_num(::google::protobuf::uint32 value) {
  set_has_num();
  num_ = value;
}

// -------------------------------------------------------------------

// gm_gs_add_item_req

// required uint32 user_id = 1;
inline bool gm_gs_add_item_req::has_user_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void gm_gs_add_item_req::set_has_user_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void gm_gs_add_item_req::clear_has_user_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void gm_gs_add_item_req::clear_user_id() {
  user_id_ = 0u;
  clear_has_user_id();
}
inline ::google::protobuf::uint32 gm_gs_add_item_req::user_id() const {
  return user_id_;
}
inline void gm_gs_add_item_req::set_user_id(::google::protobuf::uint32 value) {
  set_has_user_id();
  user_id_ = value;
}

// required uint32 item_id = 2;
inline bool gm_gs_add_item_req::has_item_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void gm_gs_add_item_req::set_has_item_id() {
  _has_bits_[0] |= 0x00000002u;
}
inline void gm_gs_add_item_req::clear_has_item_id() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void gm_gs_add_item_req::clear_item_id() {
  item_id_ = 0u;
  clear_has_item_id();
}
inline ::google::protobuf::uint32 gm_gs_add_item_req::item_id() const {
  return item_id_;
}
inline void gm_gs_add_item_req::set_item_id(::google::protobuf::uint32 value) {
  set_has_item_id();
  item_id_ = value;
}

// required uint32 num = 3;
inline bool gm_gs_add_item_req::has_num() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void gm_gs_add_item_req::set_has_num() {
  _has_bits_[0] |= 0x00000004u;
}
inline void gm_gs_add_item_req::clear_has_num() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void gm_gs_add_item_req::clear_num() {
  num_ = 0u;
  clear_has_num();
}
inline ::google::protobuf::uint32 gm_gs_add_item_req::num() const {
  return num_;
}
inline void gm_gs_add_item_req::set_num(::google::protobuf::uint32 value) {
  set_has_num();
  num_ = value;
}

// -------------------------------------------------------------------

// gs_gm_add_item_res

// required int32 error_code = 1;
inline bool gs_gm_add_item_res::has_error_code() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void gs_gm_add_item_res::set_has_error_code() {
  _has_bits_[0] |= 0x00000001u;
}
inline void gs_gm_add_item_res::clear_has_error_code() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void gs_gm_add_item_res::clear_error_code() {
  error_code_ = 0;
  clear_has_error_code();
}
inline ::google::protobuf::int32 gs_gm_add_item_res::error_code() const {
  return error_code_;
}
inline void gs_gm_add_item_res::set_error_code(::google::protobuf::int32 value) {
  set_has_error_code();
  error_code_ = value;
}

// -------------------------------------------------------------------

// gm_gs_marquee_req

// required .gm_gs_marquee_req.MARQUEE_TYPE type = 1;
inline bool gm_gs_marquee_req::has_type() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void gm_gs_marquee_req::set_has_type() {
  _has_bits_[0] |= 0x00000001u;
}
inline void gm_gs_marquee_req::clear_has_type() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void gm_gs_marquee_req::clear_type() {
  type_ = 6;
  clear_has_type();
}
inline ::gm_gs_marquee_req_MARQUEE_TYPE gm_gs_marquee_req::type() const {
  return static_cast< ::gm_gs_marquee_req_MARQUEE_TYPE >(type_);
}
inline void gm_gs_marquee_req::set_type(::gm_gs_marquee_req_MARQUEE_TYPE value) {
  assert(::gm_gs_marquee_req_MARQUEE_TYPE_IsValid(value));
  set_has_type();
  type_ = value;
}

// required string content = 2;
inline bool gm_gs_marquee_req::has_content() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void gm_gs_marquee_req::set_has_content() {
  _has_bits_[0] |= 0x00000002u;
}
inline void gm_gs_marquee_req::clear_has_content() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void gm_gs_marquee_req::clear_content() {
  if (content_ != &::google::protobuf::internal::kEmptyString) {
    content_->clear();
  }
  clear_has_content();
}
inline const ::std::string& gm_gs_marquee_req::content() const {
  return *content_;
}
inline void gm_gs_marquee_req::set_content(const ::std::string& value) {
  set_has_content();
  if (content_ == &::google::protobuf::internal::kEmptyString) {
    content_ = new ::std::string;
  }
  content_->assign(value);
}
inline void gm_gs_marquee_req::set_content(const char* value) {
  set_has_content();
  if (content_ == &::google::protobuf::internal::kEmptyString) {
    content_ = new ::std::string;
  }
  content_->assign(value);
}
inline void gm_gs_marquee_req::set_content(const char* value, size_t size) {
  set_has_content();
  if (content_ == &::google::protobuf::internal::kEmptyString) {
    content_ = new ::std::string;
  }
  content_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* gm_gs_marquee_req::mutable_content() {
  set_has_content();
  if (content_ == &::google::protobuf::internal::kEmptyString) {
    content_ = new ::std::string;
  }
  return content_;
}
inline ::std::string* gm_gs_marquee_req::release_content() {
  clear_has_content();
  if (content_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = content_;
    content_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void gm_gs_marquee_req::set_allocated_content(::std::string* content) {
  if (content_ != &::google::protobuf::internal::kEmptyString) {
    delete content_;
  }
  if (content) {
    set_has_content();
    content_ = content;
  } else {
    clear_has_content();
    content_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// -------------------------------------------------------------------

// gs_gm_marquee_res

// required int32 error_code = 1;
inline bool gs_gm_marquee_res::has_error_code() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void gs_gm_marquee_res::set_has_error_code() {
  _has_bits_[0] |= 0x00000001u;
}
inline void gs_gm_marquee_res::clear_has_error_code() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void gs_gm_marquee_res::clear_error_code() {
  error_code_ = 0;
  clear_has_error_code();
}
inline ::google::protobuf::int32 gs_gm_marquee_res::error_code() const {
  return error_code_;
}
inline void gs_gm_marquee_res::set_error_code(::google::protobuf::int32 value) {
  set_has_error_code();
  error_code_ = value;
}

// -------------------------------------------------------------------

// gm_gs_mail_req

// required .gm_gs_mail_req.MAIL_TYPE type = 1;
inline bool gm_gs_mail_req::has_type() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void gm_gs_mail_req::set_has_type() {
  _has_bits_[0] |= 0x00000001u;
}
inline void gm_gs_mail_req::clear_has_type() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void gm_gs_mail_req::clear_type() {
  type_ = 6;
  clear_has_type();
}
inline ::gm_gs_mail_req_MAIL_TYPE gm_gs_mail_req::type() const {
  return static_cast< ::gm_gs_mail_req_MAIL_TYPE >(type_);
}
inline void gm_gs_mail_req::set_type(::gm_gs_mail_req_MAIL_TYPE value) {
  assert(::gm_gs_mail_req_MAIL_TYPE_IsValid(value));
  set_has_type();
  type_ = value;
}

// repeated uint32 users = 2;
inline int gm_gs_mail_req::users_size() const {
  return users_.size();
}
inline void gm_gs_mail_req::clear_users() {
  users_.Clear();
}
inline ::google::protobuf::uint32 gm_gs_mail_req::users(int index) const {
  return users_.Get(index);
}
inline void gm_gs_mail_req::set_users(int index, ::google::protobuf::uint32 value) {
  users_.Set(index, value);
}
inline void gm_gs_mail_req::add_users(::google::protobuf::uint32 value) {
  users_.Add(value);
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >&
gm_gs_mail_req::users() const {
  return users_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint32 >*
gm_gs_mail_req::mutable_users() {
  return &users_;
}

// required string content = 3;
inline bool gm_gs_mail_req::has_content() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void gm_gs_mail_req::set_has_content() {
  _has_bits_[0] |= 0x00000004u;
}
inline void gm_gs_mail_req::clear_has_content() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void gm_gs_mail_req::clear_content() {
  if (content_ != &::google::protobuf::internal::kEmptyString) {
    content_->clear();
  }
  clear_has_content();
}
inline const ::std::string& gm_gs_mail_req::content() const {
  return *content_;
}
inline void gm_gs_mail_req::set_content(const ::std::string& value) {
  set_has_content();
  if (content_ == &::google::protobuf::internal::kEmptyString) {
    content_ = new ::std::string;
  }
  content_->assign(value);
}
inline void gm_gs_mail_req::set_content(const char* value) {
  set_has_content();
  if (content_ == &::google::protobuf::internal::kEmptyString) {
    content_ = new ::std::string;
  }
  content_->assign(value);
}
inline void gm_gs_mail_req::set_content(const char* value, size_t size) {
  set_has_content();
  if (content_ == &::google::protobuf::internal::kEmptyString) {
    content_ = new ::std::string;
  }
  content_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* gm_gs_mail_req::mutable_content() {
  set_has_content();
  if (content_ == &::google::protobuf::internal::kEmptyString) {
    content_ = new ::std::string;
  }
  return content_;
}
inline ::std::string* gm_gs_mail_req::release_content() {
  clear_has_content();
  if (content_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = content_;
    content_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void gm_gs_mail_req::set_allocated_content(::std::string* content) {
  if (content_ != &::google::protobuf::internal::kEmptyString) {
    delete content_;
  }
  if (content) {
    set_has_content();
    content_ = content;
  } else {
    clear_has_content();
    content_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// repeated .game_element elements = 4;
inline int gm_gs_mail_req::elements_size() const {
  return elements_.size();
}
inline void gm_gs_mail_req::clear_elements() {
  elements_.Clear();
}
inline const ::game_element& gm_gs_mail_req::elements(int index) const {
  return elements_.Get(index);
}
inline ::game_element* gm_gs_mail_req::mutable_elements(int index) {
  return elements_.Mutable(index);
}
inline ::game_element* gm_gs_mail_req::add_elements() {
  return elements_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::game_element >&
gm_gs_mail_req::elements() const {
  return elements_;
}
inline ::google::protobuf::RepeatedPtrField< ::game_element >*
gm_gs_mail_req::mutable_elements() {
  return &elements_;
}

// -------------------------------------------------------------------

// gs_gm_mail_res

// required int32 error_code = 1;
inline bool gs_gm_mail_res::has_error_code() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void gs_gm_mail_res::set_has_error_code() {
  _has_bits_[0] |= 0x00000001u;
}
inline void gs_gm_mail_res::clear_has_error_code() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void gs_gm_mail_res::clear_error_code() {
  error_code_ = 0;
  clear_has_error_code();
}
inline ::google::protobuf::int32 gs_gm_mail_res::error_code() const {
  return error_code_;
}
inline void gs_gm_mail_res::set_error_code(::google::protobuf::int32 value) {
  set_has_error_code();
  error_code_ = value;
}

// -------------------------------------------------------------------

// gm_gs_arena_mail_req

// -------------------------------------------------------------------

// gs_gm_arena_mail_res

// required int32 error_code = 1;
inline bool gs_gm_arena_mail_res::has_error_code() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void gs_gm_arena_mail_res::set_has_error_code() {
  _has_bits_[0] |= 0x00000001u;
}
inline void gs_gm_arena_mail_res::clear_has_error_code() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void gs_gm_arena_mail_res::clear_error_code() {
  error_code_ = 0;
  clear_has_error_code();
}
inline ::google::protobuf::int32 gs_gm_arena_mail_res::error_code() const {
  return error_code_;
}
inline void gs_gm_arena_mail_res::set_error_code(::google::protobuf::int32 value) {
  set_has_error_code();
  error_code_ = value;
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {

template <>
inline const EnumDescriptor* GetEnumDescriptor< ::gm_gs_marquee_req_MARQUEE_TYPE>() {
  return ::gm_gs_marquee_req_MARQUEE_TYPE_descriptor();
}
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::gm_gs_mail_req_MAIL_TYPE>() {
  return ::gm_gs_mail_req_MAIL_TYPE_descriptor();
}
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::e_gsgm_proto_version>() {
  return ::e_gsgm_proto_version_descriptor();
}
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::e_msg_gm_gs>() {
  return ::e_msg_gm_gs_descriptor();
}
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::e_msg_gs_gm>() {
  return ::e_msg_gs_gm_descriptor();
}
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::e_gsgm_errorcode>() {
  return ::e_gsgm_errorcode_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_gs_5fgm_5fproto_2eproto__INCLUDED
