//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: bag_item.proto
namespace bag_item
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BAG_ITEM")]
  public partial class BAG_ITEM : global::ProtoBuf.IExtensible
  {
    public BAG_ITEM() {}
    
    private string _id = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string id
    {
      get { return _id; }
      set { _id = value; }
    }
    private uint _pos = (uint)0;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"pos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint pos
    {
      get { return _pos; }
      set { _pos = value; }
    }
    private string _name_ch = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"name_ch", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name_ch
    {
      get { return _name_ch; }
      set { _name_ch = value; }
    }
    private string _name_en = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"name_en", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name_en
    {
      get { return _name_en; }
      set { _name_en = value; }
    }
    private uint _quality = (uint)0;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"quality", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint quality
    {
      get { return _quality; }
      set { _quality = value; }
    }
    private uint _health = (uint)0;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"health", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint health
    {
      get { return _health; }
      set { _health = value; }
    }
    private uint _healthGrow = (uint)0;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"healthGrow", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint healthGrow
    {
      get { return _healthGrow; }
      set { _healthGrow = value; }
    }
    private uint _damage = (uint)0;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"damage", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint damage
    {
      get { return _damage; }
      set { _damage = value; }
    }
    private uint _damageGrow = (uint)0;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"damageGrow", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint damageGrow
    {
      get { return _damageGrow; }
      set { _damageGrow = value; }
    }
    private uint _pdd = (uint)0;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"pdd", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint pdd
    {
      get { return _pdd; }
      set { _pdd = value; }
    }
    private uint _pddGrow = (uint)0;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"pddGrow", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint pddGrow
    {
      get { return _pddGrow; }
      set { _pddGrow = value; }
    }
    private uint _mdd = (uint)0;
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"mdd", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint mdd
    {
      get { return _mdd; }
      set { _mdd = value; }
    }
    private uint _mddGrow = (uint)0;
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"mddGrow", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint mddGrow
    {
      get { return _mddGrow; }
      set { _mddGrow = value; }
    }
    private uint _hitLevel = (uint)0;
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"hitLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint hitLevel
    {
      get { return _hitLevel; }
      set { _hitLevel = value; }
    }
    private uint _hitGrow = (uint)0;
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"hitGrow", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint hitGrow
    {
      get { return _hitGrow; }
      set { _hitGrow = value; }
    }
    private uint _dodgeLevel = (uint)0;
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"dodgeLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint dodgeLevel
    {
      get { return _dodgeLevel; }
      set { _dodgeLevel = value; }
    }
    private uint _dodgeGrow = (uint)0;
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"dodgeGrow", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint dodgeGrow
    {
      get { return _dodgeGrow; }
      set { _dodgeGrow = value; }
    }
    private uint _criLevel = (uint)0;
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"criLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint criLevel
    {
      get { return _criLevel; }
      set { _criLevel = value; }
    }
    private uint _criGrow = (uint)0;
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"criGrow", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint criGrow
    {
      get { return _criGrow; }
      set { _criGrow = value; }
    }
    private uint _tenacityLevel = (uint)0;
    [global::ProtoBuf.ProtoMember(20, IsRequired = false, Name=@"tenacityLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint tenacityLevel
    {
      get { return _tenacityLevel; }
      set { _tenacityLevel = value; }
    }
    private uint _tenacityGrow = (uint)0;
    [global::ProtoBuf.ProtoMember(21, IsRequired = false, Name=@"tenacityGrow", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint tenacityGrow
    {
      get { return _tenacityGrow; }
      set { _tenacityGrow = value; }
    }
    private uint _pddPierce = (uint)0;
    [global::ProtoBuf.ProtoMember(22, IsRequired = false, Name=@"pddPierce", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint pddPierce
    {
      get { return _pddPierce; }
      set { _pddPierce = value; }
    }
    private uint _pddPierceGrow = (uint)0;
    [global::ProtoBuf.ProtoMember(23, IsRequired = false, Name=@"pddPierceGrow", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint pddPierceGrow
    {
      get { return _pddPierceGrow; }
      set { _pddPierceGrow = value; }
    }
    private uint _mddPierce = (uint)0;
    [global::ProtoBuf.ProtoMember(24, IsRequired = false, Name=@"mddPierce", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint mddPierce
    {
      get { return _mddPierce; }
      set { _mddPierce = value; }
    }
    private uint _mddPierceGrow = (uint)0;
    [global::ProtoBuf.ProtoMember(25, IsRequired = false, Name=@"mddPierceGrow", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue((uint)0)]
    public uint mddPierceGrow
    {
      get { return _mddPierceGrow; }
      set { _mddPierceGrow = value; }
    }
    private string _needs = "";
    [global::ProtoBuf.ProtoMember(26, IsRequired = false, Name=@"needs", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string needs
    {
      get { return _needs; }
      set { _needs = value; }
    }
    private string _needCounts = "";
    [global::ProtoBuf.ProtoMember(27, IsRequired = false, Name=@"needCounts", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string needCounts
    {
      get { return _needCounts; }
      set { _needCounts = value; }
    }
    private string _nextId = "";
    [global::ProtoBuf.ProtoMember(28, IsRequired = false, Name=@"nextId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string nextId
    {
      get { return _nextId; }
      set { _nextId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BAG_ITEM_ARRAY")]
  public partial class BAG_ITEM_ARRAY : global::ProtoBuf.IExtensible
  {
    public BAG_ITEM_ARRAY() {}
    
    private readonly global::System.Collections.Generic.List<BAG_ITEM> _items = new global::System.Collections.Generic.List<BAG_ITEM>();
    [global::ProtoBuf.ProtoMember(1, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<BAG_ITEM> items
    {
      get { return _items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}